name: lgmc
version: '3.3.1-BETA'
main: fr.lightshoro.lgmc.Lgmc
api-version: '1.21'
description: Plugin de jeu Loup-Garou pour Minecraft (4-12 joueurs)
author: LightShoro

commands:
  lg:
    description: Commande principale du Loup-Garou
    usage: /lg <start|stop|reload|setup|help> [args]
    aliases: [loupgarou, werewolf]
  testament:
    description: Permet au capitaine de nommer son successeur
    usage: /testament <joueur>
    permission: lgmc.testament
  goodGuys:
    description: Affiche le nombre de bons joueurs restants (debug)
    usage: /goodGuys
    permission: lgmc.debug
  lgopengui:
    description: Ouvre le menu de débogage (debug)
    usage: /lgopengui
    permission: lgmc.debug
    aliases: [openlggui]
  wsaction:
    description: Commande interne pour les actions WebSocket
    usage: /wsaction <action>
    permission: lgmc.debug
  linkDiscord:
    description: Affiche le lien vers le serveur Discord du plugin
    usage: /linkDiscord
  love:
    description: Permet aux amoureux de communiquer entre eux
    usage: /love <message>
    aliases: [amour]

permissions:
  lgmc.start:
    description: Permet de démarrer une partie
    default: op
  lgmc.stop:
    description: Permet d'arrêter une partie
    default: op
  lgmc.reload:
    description: Permet de recharger la configuration
    default: op
  lgmc.setup:
    description: Permet de configurer les emplacements
    default: op
  lgmc.testament:
    description: Permet d'utiliser la commande testament
    default: true
  lgmc.debug:
    description: Permet d'utiliser les commandes de débogage
    default: op
