name: lgmc
version: '4.0.1'
main: fr.lightshoro.lgmc.Lgmc
api-version: '1.21'
description: Plugin de jeu Loup-Garou pour Minecraft (4-12 joueurs)
author: LightShoro

commands:
  lg:
    description: Commande principale du Loup-Garou
    usage: /lg <start|stop|reload|setup|gui|help> [args]
    aliases: [loupgarou, werewolf]
  goodGuys:
    description: Affiche le nombre de bons joueurs restants (debug)
    usage: /goodGuys
    permission: lgmc.debug
  wsaction:
    description: Commande interne pour les actions WebSocket
    usage: /wsaction <action>
    permission: lgmc.debug
  linkDiscord:
    description: Affiche le lien vers le serveur Discord du plugin
    usage: /linkDiscord
  love:
    description: Permet aux amoureux de communiquer entre eux
    usage: /love <message>
    aliases: [amour]

permissions:
  lgmc.start:
    description: Permet de démarrer une partie
    default: op
  lgmc.stop:
    description: Permet d'arrêter une partie
    default: op
  lgmc.reload:
    description: Permet de recharger la configuration
    default: op
  lgmc.setup:
    description: Permet de configurer les emplacements
    default: op
  lgmc.debug:
    description: Permet d'utiliser les commandes de débogage
    default: op
