name: Draft Release on Version Change

on:
  push:
    paths:
      - 'build.gradle'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from build.gradle
        id: extract_version
        run: |
          version=$(grep -Eo 'version\s*["=]\s*"[^"]+"' build.gradle | sed 's/[^"]*"\([^"]*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build JAR file
        run: ./gradlew shadowJar

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          name: Release v${{ env.version }}
          draft: true
          body: |
            ## Changes
            - Automatically drafted release for version v${{ env.version }}
          files: build/libs/lgmc-*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
